### ISSUE TITLE
error: override toolchain 'stable' is not installed

### ISSUE THREAD

**Issue by abitrolly** [rust-lang-nursery/docker-rust#8]
Trying to build 3rd party project with `rust:1.20-stretch` gives this error:
```
error: override toolchain 'stable' is not installed

info: caused by: the toolchain file at '/build/rust-toolchain' specifies an uninstalled toolchain
```
Is it possible to ship the `stable` toolchain with those images?

**Comment by sfackler** [comment]
The images use the toolchain for the specific release - `1.20.0` in the case of `rust:1.20-stretch`.

**Comment by abitrolly** [comment]
@sfackler [official blog](https://blog.rust-lang.org/2017/08/31/Rust-1.20.html) says that 1.20.0 is stable, so why the error?

**Comment by sfackler** [comment]
Rustup has multiple toolchains it can use. "stable" means the newest stable release. We can't use "stable" in the docker images because it isn't reproducible. If we did and you reran the build for the 1.19.0 image now, it'd have 1.20.0 on it. We instead use the toolchains that pin to the specific stable release.

**Comment by abitrolly** [comment]
So, the solution is to patch `rust-toolchain` file with specific version tag.

But `1.20.0` is the newest stable release, so why it still fails?

**Comment by abitrolly** [comment]
echo 1.20.0 > rust-toolchain

Fixes the issue.
